preview = true

lint.select = [
    "ALL",
]

lint.extend-ignore = [
    # Later...
    "ANN", # flake8-annotations
    "D", # pydocstyle
    "DOC",
    "TRY",
    "PLR",
    "ARG",
    "FBT",
    "ERA",
    "RUF",
    "S",
    "A",
    # False positives
    "COM812", #  	[*] missing-trailing-comma
    "ISC001",
    "TD002", #  	[ ] missing-todo-author
    "TD003", #  	[ ] missing-todo-link
    "T201", #    	[*] print
    #  Fix
    "CPY001", #  	[ ] missing-copyright-notice
    "PLC0415", # 	[ ] import-outside-top-level
    "SLF001", #  	[ ] private-member-access
    "E501", #    	[ ] line-too-long
    "PT011", #   	[ ] pytest-raises-too-broad
    "C901", #    	[ ] complex-structure
    "BLE001", #  	[ ] blind-except
    "INP001", #  	[ ] implicit-namespace-package
    "ASYNC110", #	[ ] async-busy-wait
    "EXE001", #  	[ ] shebang-not-executable
    "G004", #    	[ ] logging-f-string
    "G201", #    	[ ] logging-exc-info
    "N802", #    	[ ] invalid-function-name
    "PT012", #   	[ ] pytest-raises-with-multiple-statements
    "RET504", #  	[*] unnecessary-assign
    "FIX002", # 	[ ] line-contains-todo
    "B007", #   	[*] unused-loop-control-variable
    "B024", #   	[ ] abstract-base-class-without-abstract-method
    "B027", #   	[ ] empty-method-without-abstract-decorator
    "SIM102", # 	[ ] collapsible-if
    "F841", #   	[*] unused-variable
]
