preview = true

lint.select = [
    "ALL",
]

lint.extend-ignore = [
    # Later...
    "ANN", # flake8-annotations
    "D", # pydocstyle
    "DOC",
    "TRY",
    "PLR",
    "ARG",
    "FBT",
    "ERA",
    "RUF",
    "S",
    "A",
    # False positives
    "COM812", #  	[*] missing-trailing-comma
    "ISC001",
    "TD002", #  	[ ] missing-todo-author
    "TD003", #  	[ ] missing-todo-link
    "T201", #    	[*] print
    "RET504", #  	[*] unnecessary-assign
    "PT012", #   	[ ] pytest-raises-with-multiple-statements
    "E501", #    	[ ] line-too-long
    "FURB152", # 3.14 != Pi. This one is insane.
    # Review later
    "ASYNC109", # timeouts in asyncio
    #  Fix
    "CPY001", #  	[ ] missing-copyright-notice
    "SLF001", #  	[ ] private-member-access
    "PT011", #   	[ ] pytest-raises-too-broad
    "BLE001", #  	[ ] blind-except
    "INP001", #  	[ ] implicit-namespace-package
#    "EXE001", #  	[ ] shebang-not-executable
    "PLC1901",
]
