preview = true

lint.select = [
    "ALL",
]

lint.extend-ignore = [
    # Later...
    "ANN", # flake8-annotations
    "D", # pydocstyle
    "DOC",
    "TRY",
    "PLR",
    "ARG",
    "FBT",
    "ERA",
    "RUF",
    "S",
    "A",
    #  More specific
    "COM812", # Missing trailing comma
    "CPY001", # Missing copyright header
    "E501", # Line too long
    "S101", # Use of assert detected
    "ISC001",
    # Later
    "TD002",
    "TD003",
    "ARG002",
    "PT011",
    "PT012",
    "SLF001",
    "T201",
    # TODO
    "PLC0415", # 	[ ] import-outside-top-level
    "C901", #    	[ ] complex-structure
    "BLE001", #  	[ ] blind-except
    "INP001", #  	[ ] implicit-namespace-package
    "ASYNC110", #	[ ] async-busy-wait
    "EXE001", #  	[ ] shebang-not-executable
    "G004", #    	[ ] logging-f-string
    "G201", #    	[ ] logging-exc-info
    "N802", #    	[ ] invalid-function-name
    "RET504", #  	[*] unnecessary-assign
    "PLC2801", # 	[ ] unnecessary-dunder-call
]

